queue1=['ali', 'atefeh', 'reza', 'homa', 'amir', 'fatemeh' ]
print(queue1)
aghazadeh_1=input('enter your name:')
location1=int(input('enter your desired location:'))
queue1.insert(location1,aghazadeh_1)
aghazadeh_2=input('enter your name:')
location2=int(input('enter your desired location:'))
queue1.insert(location2,aghazadeh_2)
aghazadeh_3=input('enter your name:')
location3=int(input('enter your desired location:'))
queue1.insert(location3,aghazadeh_3)
print(queue1)